### PR TITLE
Fix problem with Java API getBodyAsSource

### LINKED ISSUE #175: getBodyAsSource in java api doesn't work
### Play WS Version (2.5.x / etc)
2.6.1

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.12.5

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_121

### Library Dependencies
play-ws-standalone 1.0.1
(a play framework 2.6.1 project created with activator)

### Expected Behavior
getBodyAsSource returns  Source<ByteString, ?>

### Actual Behavior

Exception is thrown:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.ClassCastException: play.shaded.ahc.org.asynchttpclient.netty.NettyResponse cannot be cast to org.reactivestreams.Publisher]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:252)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
Caused by: java.util.concurrent.CompletionException: java.lang.ClassCastException: play.shaded.ahc.org.asynchttpclient.netty.NettyResponse cannot be cast to org.reactivestreams.Publisher
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Caused by: java.lang.ClassCastException: play.shaded.ahc.org.asynchttpclient.netty.NettyResponse cannot be cast to org.reactivestreams.Publisher
	at play.libs.ws.ahc.StandaloneAhcWSResponse.getBodyAsSource(StandaloneAhcWSResponse.java:125)
	at play.libs.ws.ahc.AhcWSResponse.getBodyAsSource(AhcWSResponse.java:87)
	at controllers.HomeController.lambda$index$0(HomeController.java:33)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

```

### Reproducible Test Case

```java
package controllers;

import com.google.inject.Inject;
import java.util.concurrent.CompletionStage;
import play.libs.ws.DefaultBodyReadables;
import play.libs.ws.WSClient;
import play.libs.ws.WSResponse;
import play.mvc.Controller;
import play.mvc.Result;

/**
 * This controller contains an action to handle HTTP requests
 * to the application's home page.
 */
public class HomeController extends Controller implements DefaultBodyReadables {

  private final WSClient wsClient;

  @Inject
  public HomeController(WSClient wsClient) {
    this.wsClient = wsClient;
  }

  /**
   * An action that renders an HTML page with a welcome message.
   * The configuration in the <code>routes</code> file means that
   * this method will be called when the application receives a
   * <code>GET</code> request with a path of <code>/</code>.
   */
  public CompletionStage<Result> index() {
    return wsClient.url("https://www.google.com")
        .get().thenApply(WSResponse::getBodyAsSource)
        .thenApply(body -> ok(views.html.index.render()));
  }
}
```

### PR DESCRIPTION
**Pull request by marcospereira**
## Fixes

Fixes #175.

## Purpose

While this is supposed to be used with streamed responses we need to ensure the regular version also works. This changes the Java implementation to works as the Scala one.

### CODE REVIEW

File: play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java [hunk 1]
```diff
@@ -122,6 +122,15 @@
...
+     * {@code
+     * wsClient.url("https://playframework.com")
+     *         .stream() // this returns a CompletionStage<StandaloneWSResponse>
+     *         .thenApply(StandaloneWSResponse::getBodyAsSource);
+     * }
+     * </pre>
      */
-    Source<ByteString, ?> getBodyAsSource();
+    default Source<ByteString, ?> getBodyAsSource() {
+        return Source.single(getBodyAsBytes());
```
Comment (richdougherty) [inline play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java]: OK so the default implementation of a `Source` calls `getBodyAsBytes()`, which loads the entire response into memory. Do we override this somewhere to build a source from something streaming, like AHC's `response.getResponseBodyAsStream()`?

Comment (gmethvin) [inline play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java]: There's `WSResponse` and `StreamedResponse`. One is optimized for strict bodies and the other for streamed bodies. It's definitely not the greatest API, but it's consistent with the way WS has worked in the past.

Comment (richdougherty) [inline play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java]: OK that's fine, just wanted to check.

Comment (marcospereira) [inline play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSResponse.java]: Yeah, the proper API evolution, in my opinion, is to have this method only for `StreamedResponse` instead of having it in here.

**Comment by marcospereira** [comment]
Backport to 1.x.x: 06eda2e96feb1065bd1762f91cd8cdd80f3f6146
