### PR TITLE
fix: make query param order deterministic when adding params

### LINKED ISSUE #48: Should store headers and query params as a list instead of a map
Storing as a map causes re-ordering of query params which might be undesirable in some cases. It would be fine to use a `Seq[(String, String)]`.

See playframework/playframework#6884, specifically https://github.com/playframework/playframework/pull/6884#issuecomment-272674376

### PR DESCRIPTION
**Pull request by bpossolo**
# Pull Request Checklist

* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* [x] Have you [squashed your commits](https://www.playframework.com/documentation/latest/WorkingWithGit#Squashing-commits)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

## Fixes

Fixes #48 

## Purpose

Ensure deterministic query param order when adding params through the WSRequest interface.
This does not address order when adding to a query param that already contains a value.
for example
```
req.addQueryParam("p1", "v1")
req.addQueryParam("p2", "v2")
req.addQueryParam("p1, "v3")
```
will yield `p1=v1&p1=v3&p2=v2` which is still not perfect but is at least deterministic

## Background Context

I wanted to make the minimal code change to achieve deterministic behaviour.
When generating digital signatures of urls (for example of an Authorization header) it's important to have a deterministic order to be able to correctly compute the digest.

## References

https://github.com/playframework/playframework/pull/6884
https://github.com/playframework/play-ws/pull/102

### CODE REVIEW

**Comment by schmitch** [comment]
I think it would be good, to also have the example that you provided inside a test case, i.e. add `p1` twice.

**Comment by bpossolo** [comment]
haha. that's funny. i originally wrote a test for it but then deleted it because i thought it might not be desired behaviour for the future

**Comment by bpossolo** [comment]
updated

**Comment by bpossolo** [comment]
bump?

File: play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala [hunk 1]
```diff
@@ -333,6 +333,32 @@ class AhcWSRequestSpec extends Specification with Mockito with DefaultBodyReadab
         request.getUrl must contain("p1=v1")
       }
 
+      "preserve query param order" in {
```
Comment (schmitch) [inline play-ahc-ws-standalone/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala]: basically this should be split into multipe tests.

**Comment by bpossolo** [comment]
@schmitch thanks for clarifying. updated.

**Comment by bpossolo** [comment]
any chance we could get this in? its blocking a project

**Comment by ktoso** [comment]
WDYT @marcospereira ?

**Comment by bpossolo** [comment]
@richdougherty thank you!

**Comment by richdougherty** [comment]
Backported to *1.x.x* branch.
